services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekitlogicomms
    restart: unless-stopped
    network_mode: host
    command:
      - --config
      - /etc/livekit.yaml
      - --bind
      - 0.0.0.0
      - --node-ip
      - 194.163.171.40
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
