map $ssl_preread_server_name $logicomms_tls_backend {
    ~^logicommsrelay\.igportals\.eu$ livekit_turn_tls;
    default nginx_https_internal;
}

upstream livekit_turn_tls {
    server 127.0.0.1:5349;
}

upstream nginx_https_internal {
    server 127.0.0.1:4443;
}

server {
    listen 443 reuseport;
    listen [::]:443 reuseport;
    proxy_pass $logicomms_tls_backend;
    ssl_preread on;
    proxy_timeout 1h;
}
